<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">


		<xacro:property name="DEG2RAD" value="0.01745329251" />

	<!-- ======================== PALM PARAMS ===================== -->

		<xacro:property name="palm_link_z" value="0.095" />

	<!-- ====================== THUMB PARAMS ====================== -->

		<xacro:property name="links_x" value="0.0196" />
		<xacro:property name="links_y" value="0.0275" />

		<xacro:property name="link0_z" value="0.0164" />
		<xacro:property name="link1_z" value="0.0540" />
		<xacro:property name="link2_z" value="0.0384" />

		<!-- full height from joint to tip. when used,
		the radius of the finger tip sphere will be subtracted
		and one fixed link will be added for the tip. -->
		<xacro:property name="link3_z" value="0.0387" /> 
		<xacro:property name="fingerTip_r" value="0.0120" />

		<xacro:property name="offset_origin_x_const" value="0" />
		<xacro:property name="offset_origin_y_const" value="0.0435" /> <!--0.0435,   0.044981--> 
		<xacro:property name="offset_origin_z_const" value="-0.001542" /> <!--0.002298--> 
		<xacro:property name="offset_origin_z_mid_const" value="0.0007" /> <!--0.002298--> 


	<!-- ====================== THUMB PARAMS ====================== -->

		<xacro:property name="link0_t_x" value="0.0358" />
		<xacro:property name="link0_t_y" value="0.0340" />
		<xacro:property name="link0_t_z" value="0.0455" />

		<xacro:property name="link1_t_z" value="0.0177" />
		<xacro:property name="link2_t_z" value="0.0514" />
		<xacro:property name="link3_t_z" value="0.0543" />


	<!-- ========================= LIMITS ========================= -->

		<xacro:property name="joint_safety_margin" value="0.1" />
		<xacro:property name="limit_0_up" value="0.57" />
		<xacro:property name="limit_0_low" value="-0.57" />
		<xacro:property name="limit_1_up" value="1.71" />
		<xacro:property name="limit_1_low" value="-0.296" />
		<xacro:property name="limit_2_up" value="1.809" />
		<xacro:property name="limit_2_low" value="-0.274" />
		<xacro:property name="limit_3_up" value="1.718" />
		<xacro:property name="limit_3_low" value=" -0.327" />

		<xacro:property name="limit_0_t_up" value="1.496" />
		<xacro:property name="limit_0_t_low" value="0.363" />
		<xacro:property name="limit_1_t_up" value="1.263" />
		<xacro:property name="limit_1_t_low" value="-0.205" />
		<xacro:property name="limit_2_t_up" value="1.744" />
		<xacro:property name="limit_2_t_low" value="-0.289" />
		<xacro:property name="limit_3_t_up" value="1.819" />
		<xacro:property name="limit_3_t_low" value="-0.262" />

	<!-- ============================================================================= -->


    <!-- ############## Macros ################## -->
    <!-- ######################################## -->


		<!-- LEFT THUMB MACRO -->
		<xacro:macro name="thumb_left" params="base_link finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r finger_angle_p finger_angle_y sensor_on">

				<link name="link_${finger_num}0">
					<visual>				
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_12_left.dae" />
						</geometry>
						<material name="black">
							<color rgba=".2 .2 .2 1"/>
						</material>
						<origin rpy="${180*DEG2RAD} 0 0" xyz="0 0 0"/>
					</visual>   
					<collision>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_12_left.stl" />
						</geometry>
						<origin rpy="${180*DEG2RAD} 0 0" xyz="0 0 0"/>
					</collision> 
					<inertial>
						<mass value="0.0176" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="1.89273333333e-5" ixy="7.16716e-06" ixz="5.35568e-06"
								iyy="1.43008213333e-05" iyz="6.8068e-06"
								izz="1.89273333333e-05" />
					</inertial>

				</link>
			
			<joint name="joint_${finger_num}0" type="revolute">
				<axis xyz="+1 0 0"/>
				<limit effort="15" velocity="7" lower="${limit_0_t_low-joint_safety_margin}" upper="${limit_0_t_up-joint_safety_margin}" />
				<parent link="${base_link}"/>
				<child link="link_${finger_num}0"/>
				<origin rpy="${finger_angle_r} ${finger_angle_p} ${finger_angle_y}" xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
				<dynamics damping="3" friction="10"/>
			</joint>
  
				<link name="link_${finger_num}1">	
					<visual>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_13.dae" />
						</geometry>
						<material name="black">
							<color rgba=".2 .2 .2 1"/>
						</material>
					</visual>  
					<collision>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_13.stl" />
						</geometry>
					</collision>  
					<inertial>
						<mass value="0.0119" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="4.24250866667e-06" ixy="1.032087e-06" ixz="1.603525e-06"
								iyy="4.52362633333e-06" iyz="1.44808125e-06"
								izz="4.24250866667e-06" />
					</inertial>
				</link>
			
			<joint name="joint_${finger_num}1" type="revolute">
				<axis xyz="0 0 -1"/>
				<limit effort="15" velocity="7" lower="${limit_1_t_low+joint_safety_margin}" upper="${limit_1_t_up-joint_safety_margin}" />
				<parent link="link_${finger_num}0"/>
				<child link="link_${finger_num}1"/>
				<!-- LEFT -->
				<origin xyz="-0.027 -0.005 0.0399"/>
				<dynamics damping="3" friction="5"/>
			</joint>  

				<link name="link_${finger_num}2">	
					<visual>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_14.dae" />      
						</geometry>
						<material name="black">
						</material>
					</visual>   
					<collision>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_14.stl" /> 
						</geometry>
					</collision>   
					<inertial>
						<mass value="0.038" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="4.30439933333e-05" ixy="9.57068e-06" ixz="5.1205e-06" iyy="1.44451933333e-05"
								iyz="1.342825e-05" izz="4.30439933333e-05" />
					</inertial>

				</link>
			
			<joint name="joint_${finger_num}2" type="revolute">
					<axis xyz="0 1 0"/>
					<limit effort="15" velocity="7" lower="${limit_2_t_low+joint_safety_margin}" upper="${limit_2_t_up-joint_safety_margin}" />
					<parent link="link_${finger_num}1"/>
					<child link="link_${finger_num}2"/>
					<origin xyz="0 0 ${link1_t_z}"/>
					<dynamics damping="3" friction="10"/>
			</joint>  
			
				<link name="link_${finger_num}3">	
					<visual>
						<geometry>
								<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_15.dae" />            
						</geometry>
						<material name="black">
							<color rgba=".2 .2 .2 1"/>
						</material>
					</visual>  
					<collision>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_15.stl" />   
						</geometry>
					</collision> 
					<inertial>
						<mass value="0.0388" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="3.29223173333e-05" ixy="8.042076e-06" ixz="5.2283e-06"
								iyy="1.47493026667e-5" iyz="1.1283525e-5"
								izz="3.29223173333e-05" />
					</inertial>
				</link>
			
			<joint name="joint_${finger_num}3" type="revolute">
				<axis xyz="0 1 0"/>
				<limit effort="15" velocity="7" lower="${limit_3_t_low+joint_safety_margin}" upper="${limit_3_t_up-joint_safety_margin}" />
				<parent link="link_${finger_num}2"/>
				<child link="link_${finger_num}3"/>
				<origin xyz="0 0 ${link2_t_z}"/>
				<dynamics damping="3" friction="12"/>
			</joint>      
		
				<link name="link_${finger_num}_tip">	
					<visual>
						<geometry>
							<xacro:if value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/digit/visual/digit.dae"/>  </xacro:if>
							<xacro:unless value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_15_tip.dae"/>  </xacro:unless>
						</geometry>
						<material name="white">
							<color rgba=".9 .9 .9 1"/>
						</material>
					</visual>   
					<collision>
						<geometry>
							<xacro:if value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/digit/collision/digit.stl"/>  </xacro:if>
							<xacro:unless value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_15_tip.stl"/>  </xacro:unless>
						</geometry>
					</collision>  
					<inertial>
						<mass value="0.0168" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="9.68e-07" ixy="0" ixz="0"
								iyy="9.68e-07" iyz="0"
								izz="9.68e-07" />
					</inertial>
				</link>
			
			<joint name="joint_${finger_num}_tip" type="fixed">
				<parent link="link_${finger_num}3"/>
				<child link="link_${finger_num}_tip"/>
				<xacro:if value="${sensor_on}">  <origin rpy="0 0 0" xyz="0 0 0.0303"/>  </xacro:if>
				<xacro:unless value="${sensor_on}">  <origin rpy="0 0 0" xyz="0 0 ${link3_z-fingerTip_r}"/>  </xacro:unless>
			</joint>   
  
		</xacro:macro>
		<!-- END LEFT THUMB MACRO -->


		<!-- RIGHT THUMB MACRO -->
		<xacro:macro name="thumb_right" params="base_link finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r finger_angle_p finger_angle_y sensor_on">


				<link name="link_${finger_num}0">
					<visual>				
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_12_right.dae" />
						</geometry>
						<material name="black">
							<color rgba=".2 .2 .2 1"/>
						</material>
						<origin rpy="${180*DEG2RAD} 0 0" xyz="0 0 0"/>
					</visual>   
					<collision>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_12_right.stl" />
						</geometry>
						<origin rpy="${180*DEG2RAD} 0 0" xyz="0 0 0"/>
					</collision> 
					<inertial>
						<mass value="0.0176" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="1.89273333333e-5" ixy="7.16716e-06" ixz="5.35568e-06"
								iyy="1.43008213333e-05" iyz="6.8068e-06"
								izz="1.89273333333e-05" />
					</inertial>
				</link>
			
			<joint name="joint_${finger_num}0" type="revolute">
				<axis xyz="-1 0 0"/>
				<limit effort="15" velocity="7" lower="${limit_0_t_low-joint_safety_margin}" upper="${limit_0_t_up-joint_safety_margin}" />
				<parent link="${base_link}"/>
				<child link="link_${finger_num}0"/>
				<origin rpy="${finger_angle_r} ${finger_angle_p} ${finger_angle_y}" xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
				<dynamics damping="3" friction="10"/>
			</joint>
			
               <link name="link_${finger_num}1">   
                    <visual>
                        <geometry>
                            <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_13.dae" />
                        </geometry>
                        <material name="black">
                            <color rgba=".2 .2 .2 1"/>
                        </material>
                    </visual>  
                    <collision>
                        <geometry>
                            <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_13.stl" />
                        </geometry>
                    </collision>  
					<inertial>
						<mass value="0.0119" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="4.24250866667e-06" ixy="1.032087e-06" ixz="1.603525e-06"
								iyy="4.52362633333e-06" iyz="1.44808125e-06"
								izz="4.24250866667e-06" />
					</inertial>

                </link>
            
            <joint name="joint_${finger_num}1" type="revolute">
                <axis xyz="0 0 1"/>
                <limit effort="15" velocity="7" lower="${limit_1_t_low+joint_safety_margin}" upper="${limit_1_t_up-joint_safety_margin}" />
                <parent link="link_${finger_num}0"/>
                <child link="link_${finger_num}1"/>
                <!-- RIGHT -->    
                <origin xyz="-0.027 0.005 0.0399"/>
                <dynamics damping="3" friction="5"/>
            </joint>  

				<link name="link_${finger_num}2">
					<visual>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_14.dae" />
						</geometry>
						<material name="black">
							<color rgba=".2 .2 .2 1"/>
						</material>
					</visual>
					<collision>
						<geometry>
							 <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_14.stl" />
						</geometry>
					</collision>
					<inertial>
						<mass value="0.038" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="4.30439933333e-05" ixy="9.57068e-06" ixz="5.1205e-06" iyy="1.44451933333e-05"
								iyz="1.342825e-05" izz="4.30439933333e-05" />
					</inertial>
				</link>

			<joint name="joint_${finger_num}2" type="revolute">
				<axis xyz="0 1 0"/>
                <limit effort="15" velocity="7" lower="${limit_2_t_low+joint_safety_margin}" upper="${limit_2_t_up-joint_safety_margin}" />
                <parent link="link_${finger_num}1"/>
                <child link="link_${finger_num}2"/>
				<origin xyz="0 0 ${link1_t_z}"/>
				<dynamics damping="3" friction="10"/>
			</joint>

				<link name="link_${finger_num}3">
					<visual>
						<geometry>
						<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_15.dae" />
						</geometry>
						<material name="black">
							<color rgba=".2 .2 .2 1"/>
						</material>
					</visual>
					<collision>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_15.stl" />
						</geometry>
					</collision>
					<inertial>
						<mass value="0.0388" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="3.29223173333e-05" ixy="8.042076e-06" ixz="5.2283e-06"
								iyy="1.47493026667e-5" iyz="1.1283525e-5"
								izz="3.29223173333e-05" />
					</inertial>

				</link>

			<joint name="joint_${finger_num}3" type="revolute">
				<axis xyz="0 1 0"/>
                <limit effort="15" velocity="7" lower="${limit_3_t_low+joint_safety_margin}" upper="${limit_3_t_up-joint_safety_margin}" />
                <parent link="link_${finger_num}2"/>
                <child link="link_${finger_num}3"/>
				<origin xyz="0 0 ${link2_t_z}"/>
				<dynamics damping="3" friction="12"/>
			</joint>

				<link name="link_${finger_num}_tip">	
					<visual>
						<geometry>
							<xacro:if value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/digit/visual/digit.dae"/>  </xacro:if>
							<xacro:unless value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_15_tip.dae"/>  </xacro:unless>
						</geometry>
						<material name="white">
							<color rgba=".9 .9 .9 1"/>
						</material>
					</visual>   
					<collision>
						<geometry>
							<xacro:if value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/digit/collision/digit.stl"/>  </xacro:if>
							<xacro:unless value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_15_tip.stl"/>  </xacro:unless>
						</geometry>
					</collision>  
					<inertial>
						<mass value="0.0168" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="9.68e-07" ixy="0" ixz="0"
								iyy="9.68e-07" iyz="0"
								izz="9.68e-07" />
					</inertial>

				</link>
			
			<joint name="joint_${finger_num}_tip" type="fixed">
				<parent link="link_${finger_num}3"/>
				<child link="link_${finger_num}_tip"/>
				<xacro:if value="${sensor_on}">  <origin rpy="0 0 0" xyz="0 0 0.0303"/>  </xacro:if>
				<xacro:unless value="${sensor_on}">  <origin rpy="0 0 0" xyz="0 0 ${link3_z-fingerTip_r}"/>  </xacro:unless>
			</joint>   		
		</xacro:macro>
		<!-- END RIGHT THUMB MACRO -->


		<!-- FINGER MACRO -->
		<xacro:macro name="finger" params="base_link finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r sensor_on">

				<link name="link_${finger_num}0">	
					<visual>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_0.dae" />
						</geometry>
						<material name="black"/>
					</visual>
					<collision>
						<geometry>
							<mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_0.stl" />
						</geometry>
					</collision>  
					<inertial>
						<mass value="0.0176" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="1.89273333333e-5" ixy="7.16716e-06" ixz="5.35568e-06"
							iyy="1.43008213333e-05" iyz="6.8068e-06"
							izz="1.89273333333e-05" />
					</inertial> 
				</link>
  
			<joint name="joint_${finger_num}0" type="revolute">
				<axis xyz="0 0 1"/>
				<limit effort="15" velocity="7" lower="${limit_0_low+joint_safety_margin}" upper="${limit_0_up-joint_safety_margin}" />
				<parent link="${base_link}"/>
				<child link="link_${finger_num}0"/>
				<origin rpy="${finger_angle_r} 0 0" xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
				<dynamics damping="3" friction="10"/>
			</joint>
  
                <link name="link_${finger_num}1">
                    <visual>
                        <geometry>
                            <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_1.dae" />
                        </geometry>
                        <material name="black"/>
                    </visual>   
                    <collision>
                        <geometry>
                            <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_1.stl" />
                        </geometry>
                    </collision>  
					<inertial>
						<mass value="0.0119" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="4.24250866667e-06" ixy="1.032087e-06" ixz="1.603525e-06"
								iyy="4.52362633333e-06" iyz="1.44808125e-06"
								izz="4.24250866667e-06" />
					</inertial>
                </link>
            
            <joint name="joint_${finger_num}1" type="revolute">
                <limit effort="15" velocity="7" lower="${limit_1_low+joint_safety_margin}" upper="${limit_1_up-joint_safety_margin}" />
                <axis xyz="0 1 0"/>
                <parent link="link_${finger_num}0"/>
                <child link="link_${finger_num}1"/>
                <origin xyz="0 0 ${link0_z}"/>
				<dynamics damping="3" friction="5"/>
            </joint>  

                <link name="link_${finger_num}2">   
                    <visual>
                        <geometry>
                            <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_2.dae" />
                        </geometry>
                        <material name="black"/>
                    </visual>  
                    <collision>
                        <geometry>
                            <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_2.stl" />
                        </geometry>
                    </collision> 
					<inertial>
						<mass value="0.038" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="4.30439933333e-05" ixy="9.57068e-06" ixz="5.1205e-06" iyy="1.44451933333e-05"
								iyz="1.342825e-05" izz="4.30439933333e-05" />
					</inertial>
                </link>
            
            <joint name="joint_${finger_num}2" type="revolute">
                <axis xyz="0 1 0"/>
                <limit effort="15" velocity="7" lower="${limit_2_low+joint_safety_margin}" upper="${limit_2_up-joint_safety_margin}" />
                <parent link="link_${finger_num}1"/>
                <child link="link_${finger_num}2"/>
                <origin xyz="0 0 ${link1_z}"/>
				<dynamics damping="8" friction="10"/>
            </joint>  

                <link name="link_${finger_num}3">   
                    <visual>
                        <geometry>
                            <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_3.dae" />
                        </geometry>
                        <material name="black"/>
                    </visual>   
                    <collision>
                        <geometry>
                            <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_3.stl" />
                        </geometry>
                    </collision>  
					<inertial>
						<mass value="0.0388" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="3.29223173333e-05" ixy="8.042076e-06" ixz="5.2283e-06"
								iyy="1.47493026667e-5" iyz="1.1283525e-5"
								izz="3.29223173333e-05" />
					</inertial>
                </link>
                    
            <joint name="joint_${finger_num}3" type="revolute">
                <axis xyz="0 1 0"/>
                <limit effort="15" velocity="7" lower="${limit_3_low+joint_safety_margin}" upper="${limit_3_up-joint_safety_margin}" />
                <parent link="link_${finger_num}2"/>
                <child link="link_${finger_num}3"/>
                <origin xyz="0 0 ${link2_z}"/>
				<dynamics damping="10" friction="12"/>
            </joint>      

                <link name="link_${finger_num}_tip">    
                    <visual>
                        <geometry>
                            <xacro:if value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/digit/visual/digit.dae"/>  </xacro:if>
                            <xacro:unless value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/visual/link_15_tip.dae"/>  </xacro:unless>
                        </geometry>
                        <material name="white">
                            <color rgba=".9 .9 .9 1"/>
                        </material>
                    </visual>  
                    <collision>
                        <geometry>
                            <xacro:if value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/digit/collision/digit.stl"/>  </xacro:if>
                            <xacro:unless value="${sensor_on}">  <mesh filename="package://bullet_grasp_simulator/meshes/allegro_hand/collision/link_15_tip.stl"/>  </xacro:unless>                       
						</geometry>
                    </collision> 
					<inertial>
						<mass value="0.0168" />
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<inertia ixx="9.68e-07" ixy="0" ixz="0"
								iyy="9.68e-07" iyz="0"
								izz="9.68e-07" />
					</inertial>
                </link>

            <joint name="joint_${finger_num}_tip" type="fixed">
                <parent link="link_${finger_num}3"/>
                <child link="link_${finger_num}_tip"/>
                <xacro:if value="${sensor_on}">  <origin rpy="0 0 0" xyz="0 0 0.0147"/> </xacro:if>
                <xacro:unless value="${sensor_on}">  <origin rpy="0 0 0" xyz="0 0 ${link3_z-fingerTip_r}"/>  </xacro:unless>
            </joint>   

		</xacro:macro>
		<!-- END FINGER MACRO -->


    <!-- ######################################## -->
    <!-- ############## Macros ################## -->





</robot>
